### ISSUE TITLE
Scrolling Issues

### ISSUE THREAD

**Issue by DrLynch** [ETS-Next-Gen/writing_observer#145]
In classroom observations we noted that teachers are often using small touchscreens or other pad devices.  This can make scrolling difficult given the small margin space on our interfaces.  Therefore as an enhancement we need to consider design improvements with tablet users in mind.

**Comment by bradley-erickson** [comment]
In the recent dashboards, more space was added between students to provide more space to grab while in a tablet. Closing this for now.
