### ISSUE TITLE
Switch extension to a sane process.

### ISSUE THREAD

**Issue by pmitros** [ETS-Next-Gen/writing_observer#53]
Right now, the extension is flat JavaScript, laid out for an extension. This works well for small extensions, but will not work well as we add functionality. 

For example, I'd like to have a generic event logger library shared between extension and other places, but we can't include libraries sanely. 

We don't have CI/CD, testing, ESLint, etc. either. 

The universe suggests there are boilerplates like:

https://oss.mobilefirst.me/extension-cli/
https://github.com/dutiyesh/chrome-extension-cli#readme

It'd make sense to evaluate these, pick one, and use it. 

See also: https://dev.to/anilkumarum/3-ways-to-add-npm-package-in-chrome-extension-3e3b

**Comment by bradley-erickson** [comment]
This has been resolved with a recent pull request.
